### ISSUE TITLE
🐍 Make the Robyn R demo executable with Python

### ISSUE THREAD

**Issue by mattigrthr** [kuwala-io/kuwala#109]
As preparation for #93, we need to make the Robyn model executable in Python. The Robyn model is written in R but our backend structure runs with Python so we need to find a way to execute the R functions from our backend.

There is a Python package that tries to do exactly that: [`rpy2`](https://github.com/rpy2/rpy2)

As a first flow, we want to run the Robyn model based on the demo data Meta provided.

The code should be placed under `kuwala/core/backend/app/models`.

Steps:
- [x] Export the demo data to CSV files (outside of the main repo)
- [x] Import the demo data into the Kuwala Postgres database manually (new tables for each marketing channel and one for the revenue)
- [x] Load the data from the Postgres and pass it to Robyn
- [x] Run the Robyn model
- [x] Export the results to CSV files and store them under `kuwala/tmp/kuwala/models/robyn`
- [x] Load the results into a table in the Postgres called `robyn_results`

Technical resources:
- [rpy2 documentation](https://rpy2.github.io/doc/v3.4.x/html/introduction.html#r-packages)
- [Robyn repository](https://github.com/facebookexperimental/Robyn)

**Comment by IritaSee** [comment]
<img width="712" alt="Screenshot 2022-03-29 at 17 39 52" src="https://user-images.githubusercontent.com/48131951/160593892-6b8103d0-2e3b-4c1c-8b51-855bcb647035.png">
A bit unfortunate, when I run the data fitting for Robyn in the wrapper, this occurs

**Comment by IritaSee** [comment]
> <img alt="Screenshot 2022-03-29 at 17 39 52" width="712" src="https://user-images.githubusercontent.com/48131951/160593892-6b8103d0-2e3b-4c1c-8b51-855bcb647035.png">
> 
> A bit unfortunate, when I run the data fitting for Robyn in the wrapper, this occurs

Related to this, I already have some solutions, and will be discussed in #111
