### ISSUE TITLE
Google-POI: Category mapping

### ISSUE THREAD

**Issue by mattigrthr** [kuwala-io/kuwala#11]
The pipeline should also convert the Google category tags into the same high-level categories as it is done in the OSM-POI pipeline. This makes merging the data sources possible also on the category level and enables queries based on categories for Google POIs.

**Comment by alcoholfreebear** [comment]
assign me. :)

**Comment by mattigrthr** [comment]
Here is some more info about the requirements. You can basically orient yourself along the `osm-poi` pipeline. Even though it's written in JS, you can easily transfer the functionality to Python.

You can find the category mapping for the OSM POI categories under `kuwala/kuwala-pipelines/osm-poi/resources/categories.json`. For the Google POI category mapping, you should create a file with the same structure (the same high-level categories) under `kuwala/kuwala-pipelines/`**`google-poi`**`/resources/categories.json`.

In `kuwala/kuwala-pipelines/osm-poi/src/data/processor/pbfParser/tagParser/tagParser.js`, we have already a mapping function written in JS. 

We already retrieve the unmapped category tags from Google in `kuwala/kuwala-pipelines/google-poi/src/routes/poi_information.py`. The mapped categories should be stored in a separate property to do more granular mapping in the future possibly. 

To generate more examples, we suggest using Postman. We don't expect you to map hundreds of category tags. If a tag doesn't exist in a high-level category, it should be added under `misc` in the `categories.json` so it is possible to attribute it to a fitting high-level category later on.
