### ISSUE TITLE
Population-Density: Filter results by demographic group

### ISSUE THREAD

**Issue by mattigrthr** [kuwala-io/kuwala#2]
Instead of returning all demographic groups, it should be possible to pass a query parameter to return specific groups.

**Comment by Arun-kc** [comment]
Hi @mattigrthr, can I try working on this issue? Would be nice if you could explain a bit more. In the codebase, I saw we are already filtering the data out by demographic group (FYI I just went through the codebase in GitHub itself, haven't setup the environment in my sys yet)

**Comment by mattigrthr** [comment]
Hi @Arun-kc, this issue is a bit outdated. 😅 Back in April we had an API for getting the population density. Then we switched to loading everything into a Neo4j. But tomorrow I'm going to merge the latest changes where we switched to a Postgres + dbt setup. So this issue is not relevant anymore. I'm sure we'll find another issue. I'll message you on Slack.

**Comment by Arun-kc** [comment]
It's ok @mattigrthr , happens 😂
Hope to do some contributions soon 🙌🙌
(Just a thought, it's better to close all the issues that's outdated 🤔)

**Comment by mattigrthr** [comment]
Yes, I'll do that once I merged the new structure. ✌🏽
