### ISSUE TITLE
Population-Density: Query a hex-grid within defined boundaries and set hex size

### ISSUE THREAD

**Issue by DHRAF** [kuwala-io/kuwala#38]
That could be potentially more efficient than creating a loop to query each hex in a grid.

Hex size would also help a lot in order to look at bigger regions.

**Comment by mattigrthr** [comment]
To clarify the issue here, you want to send a query with a specific boundary (e.g., provided as GeoJSON) and return all hexagons with their respective population values within that boundary at a given resolution, right?

**Comment by DHRAF** [comment]
Correct!
