### ISSUE TITLE
Notebook: Save results as data set

### ISSUE THREAD

**Issue by mattigrthr** [kuwala-io/kuwala#46]
After running all transformations, the results have to be saved in a dedicated format. In the beginning we should provide CSV, Parquet and JSON.

Depends on #45

**Comment by SamDuan** [comment]
@mattigrthr is this request still on the todo list? If so, I'm happy to take a crack at it.

**Comment by mattigrthr** [comment]
Hi @SamDuan, yes, this one is still on the TODO list! 💯 Great, you'll be tackling this. 💪🏽

**Comment by SamDuan** [comment]
@mattigrthr couple questions about this feature:
1. Shall I just add another section at the end of the notebook, showing how to export `result` dataframe as CSV, Parquet and Json? Or you are thinking something else?
2. And create a folder named e.g. `result` under `kuwala`?

**Comment by mattigrthr** [comment]
@SamDuan, yes, that's exactly what I was thinking as well. CSV, Parquet, and JSON are the most common formats. Also, having another `result` folder under `kuwala` in the Jupyter environment is a good way. The `result` folder should be structured with subdirectories according to which notebook the files belong to IMO, and then people can easily download the files from there.

In the future, we can have more connectors to destinations such as data warehouses or S3. But these would be separate issues.
