### ISSUE TITLE
Population-Density: Show warning and let user retry input when no demographic group has been selected

### ISSUE THREAD

**Issue by Wolfie432** [kuwala-io/kuwala#54]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    Processor.start(files, output_dir)
  File "/opt/app/src/Processor.py", line 31, in start
    map(lambda f: os.path.getsize(f['path'] + os.listdir(f['path'])[0]) / math.pow(1024, 2), files)
TypeError: reduce() of empty sequence with no initial value
ERROR: 1

I am facing the following error while running the docker-compose run  population-density command, please throw some light

**Comment by mattigrthr** [comment]
The error suggests that their are no files passed to the processor. What the pipeline does is to ask you first for which country and demographic groups you want to process the data. 

Which country and demographic groups did you select? Knowing this I can better try to reproduce the error. 

Also, if the download was successful, you can find the downloaded files under `kuwala/kuwala/tmp/kuwala/populationFiles`. If there are no files, was there an additional warning or error before the exception you posted?

**Comment by Wolfie432** [comment]
![image](https://user-images.githubusercontent.com/67095195/129862252-147977f2-d2a2-4e93-97d6-aec15bfcb717.png)

Hello sir, thank you for a detailed reply.
I did `sudo docker-compose run  population-density`
then it prompted to ask regarding which country do I want to download the population data.
I chose Maldives.
then I went for children_under_five
and then the error can be shown in above screenshot.

Also, if the download was successful, you can find the downloaded files under `kuwala/kuwala/tmp/kuwala/populationFiles`. If there are no files, was there an additional warning or error before the exception you posted?: there are no files in the above given location, also warnings could be seen in the above screenshot.

Thank you

**Comment by mattigrthr** [comment]
Thanks for the screenshot! I just ran it with the same selections and I believe when picking the demographic group you moved the cursor but didn't press `<space>` to select. It's a multi-select prompt so you can process all groups at once. How to select and deselect is written next to the question.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/28758040/129866604-37f1bb80-4816-498e-bb7d-d4e9615c486a.png">

Once you selected the demographic groups, they also appear in an array behind the question where on your screenshot is `"done"` right now. This is the complete output for the run with Maldives + children_under_five.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/28758040/129866870-24fc44ac-1731-4e67-95f1-a8f5d55de5a6.png">

However, I have to admit that this may not be very obvious at the first glance. So we should include a warning that no demographic group has been selected and let the user retry it. I will rename this issue to reflect that.

**Comment by Wolfie432** [comment]
Thanks sir, I am able to run it fully now.
