### ISSUE TITLE
Can't build docker image due to missing osm-parquetizer

### ISSUE THREAD

**Issue by abachant** [kuwala-io/kuwala#56]
When I try to run step 2 in the readme I get this output:
```
ERROR: No such service: osm-parquetizer
```
Running on mac OS Big Sur 11.5.2
docker-compose version 1.29.2, build 5becea4c

**Comment by mattigrthr** [comment]
There is a gap in our documentation. `osm-parquetizer` is a git submodule. When cloning the repo for the first time you need to run from the root directory:

```
git submodule update --init --recursive
```

Then the folder under `kuwala/kuwala/pipelines/osm-poi/osm-parquetizer` should not be empty anymore.

Sorry for your struggle. We will add this to the docs.
